{
 "title": "NDK_Dashboard",
 "description": "Works with NDK Exporter\nhttps://github.com/rathnaarun77/ndk-exporter.git",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "NDK",
   "type": "text",
   "description": "Nutanix Dataservices for Kubernetes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"width: 134px; height: 134px; overflow: hidden; position: relative;\">\n  <img src=\"https://github.com/rathnaarun77/ndk-exporter/blob/main/nutanix_logo_new.png?raw=true\" style=\"position: absolute; top: -50%; left: -50%; width: auto; height: auto;\"/>\n</div>"
   }
  },
  {
   "title": "Applications",
   "type": "stat",
   "description": "Total aplication managed by NDK",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", ndk_application_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count by (ready_to_use) (ndk_application_snapshot_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restores",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "count by (completed) (ndk_application_restore_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "ndk_application_info", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "App Policies",
   "type": "stat",
   "description": "Application Protection Policies",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (ndk_protectionplan_status_available)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Clusters",
   "type": "stat",
   "description": "Remote NDK Clusters",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (ndk_remote_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backup and Restore Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count (ndk_application_snapshot_info)",
     "legendFormat": "Snapshots"
    },
    {
     "expr": "count (ndk_application_restore_info)",
     "legendFormat": "Restores"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "ndk_application_snapshot_info", "legendFormat": "__auto" },
    {
     "expr": "ndk_application_snapshot_creation_timestamp_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "ndk_application_snapshot_expiration_timestamp_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restores",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "ndk_application_restore_info", "legendFormat": "__auto" },
    {
     "expr": "ndk_application_restore_start_timestamp_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "ndk_application_restore_end_timestamp_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Clusters",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "ndk_remote_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "ndk_applicationsnapshotreplication_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Policies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "ndk_appprotection_plan_info", "legendFormat": "__auto" },
    {
     "expr": "ndk_appprotection_plan_status_available",
     "legendFormat": "__auto"
    },
    {
     "expr": "ndk_appprotection_plan_status_degraded",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}